import streamlit as st
import urllib.parse
from datetime import datetime

st.set_page_config(page_title="The Cutting Edge", page_icon="🌱", layout="centered")

st.markdown("""
<style>
    .stApp { background: linear-gradient(135deg, #2d5a27 0%, #4a9c3d 50%, #3d8a35 100%); }
    .main-header { text-align: center; color: white; padding: 20px 0; }
    .main-header h1 { color: #fffef5; font-size: 2.5rem; margin-bottom: 0; }
    .main-header .highlight { color: #f5a623; }
    .card { background: #fffef5; border-radius: 20px; padding: 25px; margin: 15px 0; border-top: 6px solid #4a9c3d; }
    .category-badge { background: #4a9c3d; color: white; padding: 5px 15px; border-radius: 20px; font-size: 0.8rem; font-weight: bold; display: inline-block; margin-bottom: 15px; }
    .surface-text { color: #666; font-style: italic; padding: 10px 0; border-bottom: 2px dashed #ddd; margin-bottom: 15px; }
    .reason-label { color: #f5a623; font-weight: bold; font-size: 0.8rem; text-transform: uppercase; }
    .reason-text { color: #2d5a27; font-size: 1.3rem; font-weight: bold; line-height: 1.4; }
    .approach-label { color: #4a9c3d; font-weight: bold; font-size: 0.8rem; text-transform: uppercase; }
    .approach-text { color: #2d5a27; font-size: 1.1rem; line-height: 1.6; }
    .success-box { background: #d4edda; border-radius: 10px; padding: 15px; text-align: center; color: #2d5a27; font-weight: bold; }
    .guide-output { background: linear-gradient(135deg, #e8f5e6, #d4edda); border-radius: 15px; padding: 20px; margin-top: 20px; border-left: 5px solid #4a9c3d; }
    .guide-section { margin-bottom: 15px; }
    .guide-label { color: #4a9c3d; font-weight: bold; font-size: 0.75rem; text-transform: uppercase; margin-bottom: 5px; }
    .guide-text { color: #2d5a27; font-size: 1.1rem; line-height: 1.6; }
</style>
""", unsafe_allow_html=True)

objections = [
    {"id": 1, "category": "Commitment", "surface": "I only need a one-time service", "reason": "They don't want to be locked into a rigid schedule", "rebuttal": "The three cuts are completely flexible — use them whenever you need, no set schedule required. Life happens, and we work around it."},
    {"id": 2, "category": "Commitment", "surface": "I only need a one-time service", "reason": "They're worried about paying upfront for services they might not use", "rebuttal": "No upfront payment ever. You're only charged three days after each service is completed. You're never paying for something you haven't received yet."},
    {"id": 4, "category": "Commitment", "surface": "I only need a one-time service", "reason": "They're testing the waters and don't trust committing to a new company", "rebuttal": "That's exactly why we have the three-day quality window — you see the work, inspect it, and we fix any mistakes BEFORE payment. It's basically a trial run with zero risk."},
    {"id": 5, "category": "Timing", "surface": "I need someone to come out today", "reason": "They have a genuine urgent situation (event, guests coming, etc.)", "rebuttal": "After signup, you can message your crew directly through the app and ask if they can fit you in sooner. No guarantees, but it's worth a shot and crews often accommodate when they can."},
    {"id": 6, "category": "Timing", "surface": "I got an HOA notice and need it done ASAP", "reason": "They're stressed about a violation or fine deadline", "rebuttal": "I totally understand the pressure. While we do have a 48-hour turnaround, we can send you an email confirmation right after signup that you can forward to your HOA to show you have service scheduled. That usually buys you the time you need."},
    {"id": 7, "category": "Timing", "surface": "I need someone to come out today", "reason": "They're impatient and think all companies take forever", "rebuttal": "We have the fastest turnaround in the industry — 48 hours for first service. We price your yard before we show up, so there's no waiting around for quotes. Most competitors can't touch that speed."},
    {"id": 8, "category": "Timing", "surface": "48 hours is too long to wait", "reason": "They're comparing to a neighbor kid who can come over anytime", "rebuttal": "With us you get insured professionals, guaranteed quality, and a team to back it up if anything goes wrong. That 48 hours gets you reliability you can count on every time."},
    {"id": 9, "category": "Timing", "surface": "I'll just call back when I actually need it", "reason": "They don't want to plan ahead or commit to anything now", "rebuttal": "Totally fine — but keep in mind there's still a 48-hour window when you do call. If you grab a spot now, you lock in availability and can cancel free up to 48 hours before if plans change."},
    {"id": 10, "category": "Price", "surface": "Your prices are too high", "reason": "They're comparing to the cheapest option they can find", "rebuttal": "Every pro is verified and insured, so you're not gambling on some random person. You're paying for peace of mind and consistency, not just a mow."},
    {"id": 11, "category": "Price", "surface": "Your prices are too high", "reason": "They've been burned before paying good money for bad service", "rebuttal": "You have a full three days after service to inspect everything before you're charged. See an issue? Let us know and we send someone to fix it. We have a whole team dedicated to making it right."},
    {"id": 12, "category": "Price", "surface": "Your prices are too high", "reason": "They don't understand what's included in the service", "rebuttal": "That price covers the full service plus our quality guarantee, insurance, and support team. What specifically were you hoping to get done? Let me make sure we're comparing apples to apples."},
    {"id": 13, "category": "Price", "surface": "I found someone cheaper", "reason": "They're price-focused but haven't thought about risk", "rebuttal": "Are they insured? What happens if they damage something or don't show up? With us, you're protected — and you don't pay until three days after service when you've confirmed you're happy."},
    {"id": 14, "category": "Shopping Around", "surface": "I'm getting other quotes first", "reason": "They already have a quote from another company but something's off about it", "rebuttal": "What's giving you hesitation with them? (Let them talk — then position how we compare on whatever concern they raise.)"},
    {"id": 15, "category": "Shopping Around", "surface": "I'm not ready to commit yet", "reason": "They haven't actually gotten other quotes, just stalling", "rebuttal": "Is there something specific holding you back? (Probe for the real objection — it's usually price, trust, or timing. Then address that directly.)"},
    {"id": 16, "category": "Shopping Around", "surface": "I want to think about it", "reason": "They're interested but genuinely need time to decide", "rebuttal": "Totally fair. Want me to save a spot on the schedule for you? No charge until after service, and you can cancel up to 48 hours before if you change your mind or find someone else."},
    {"id": 17, "category": "Shopping Around", "surface": "I need to talk to my spouse first", "reason": "They actually do need to check with someone else", "rebuttal": "Of course! I can hold a spot for you so you don't lose availability. No charge until after service, and you can cancel anytime up to 48 hours before. Want me to lock that in while you chat with them?"},
    {"id": 18, "category": "Shopping Around", "surface": "I need to talk to my spouse first", "reason": "They're using it as an excuse to get off the phone", "rebuttal": "Absolutely, I get it. Is there anything I can answer right now that might help that conversation? (Probe gently — often there's a real objection hiding underneath.)"},
    {"id": 19, "category": "Payment", "surface": "Can I pay with cash?", "reason": "They don't like having cards on file with companies", "rebuttal": "Card-only actually protects you — your bank has your back if anything ever goes wrong. It's an extra layer of security you don't get with cash."},
    {"id": 20, "category": "Payment", "surface": "Can I pay with cash?", "reason": "They just prefer cash transactions in general", "rebuttal": "It's actually a benefit for everyone — crews know they're guaranteed payment, which means they show up motivated and ready to do great work. Protects you and them."},
    {"id": 21, "category": "Payment", "surface": "I don't want my card charged automatically", "reason": "They're worried about unauthorized or surprise charges", "rebuttal": "You won't be charged until three days after service — and only after you've had time to inspect the work. If there's any issue, you contact us before that window closes and we make it right first."},
    {"id": 22, "category": "Fees", "surface": "What's this long grass fee?", "reason": "They're worried about surprise charges after the fact", "rebuttal": "We mention it upfront specifically so there are no surprises. If your grass is under 9 inches, it won't apply. We're just being transparent in case it's relevant to your yard."},
    {"id": 23, "category": "Fees", "surface": "That long grass fee seems unfair", "reason": "They think it's just a way to upcharge them", "rebuttal": "It's actually industry standard — overgrown yards take significantly more time and wear on equipment. We keep it fair: only applies at 9 inches or above, and we're telling you NOW so there are no surprises."},
    {"id": 24, "category": "Trust", "surface": "I've never heard of your company", "reason": "They're skeptical of trying something new", "rebuttal": "That's fair — if you Google us, you'll see we have amazing reviews. And because you don't pay until three days after service, you can see the quality for yourself before any money changes hands."},
    {"id": 25, "category": "Trust", "surface": "How do I know the crew will do a good job?", "reason": "They've had bad experiences with lawn services before", "rebuttal": "Every pro is insured and vetted. Plus you have three full days to inspect before you're charged. If anything's off, our quality team fixes it — that's literally their whole job."},
    {"id": 26, "category": "Trust", "surface": "What if I don't like the service?", "reason": "They want to know there's a safety net", "rebuttal": "You have a three-day window after service to review everything before you're charged. If something's not right, reach out and we'll send someone to correct it. You're never stuck paying for work you're not happy with."}
]

dispositions = ["Already Hired A Provider", "Arrival Time", "Broken Address", "Callback", "Dead Air", "Disconnected", "Drop Voicemail", "Duplicate", "Frequency Minimum", "Insufficient Capacity", "Junk Contact", "Less Than 48 Hour Turn-Around", "LGF - Long Grass Fee", "Minimum Cuts Requirement", "No In-Person Quote", "Not DM", "Timing - Unable to Qualify", "Not Qualified - Refuse Contact", "Not Qualified - Telemarketer", "Order Complexity", "Out Of Area", "Oversized Lot", "Pre Paid Card", "Price", "Property Manager", "Provider Inquiry", "Rejected CC", "Rejected CC - Online Signup", "Rejected Subcontracting", "Services Not Offered", "Support Call", "Next Spring", "Test"]

guide_scenarios = {
    "One-Time Service": {"openings": {"Empathetic": "I totally hear you — a lot of people start out thinking they just need a one-time cleanup.", "Curious": "Got it! Can I ask what's prompting the need right now? Just trying to get a sense of what you're dealing with.", "Direct": "Here's the good news — we actually make it super flexible for exactly that reason."}, "points": {"Flexible scheduling": "You can use your three cuts whenever you want — no set schedule, no pressure. Life happens, and we work around it.", "No upfront payment": "You never pay upfront. We only charge three days after each service is done, so you see the work first.", "Pro learns your lawn": "When the same pro comes back, they get to know your lawn and your preferences. Better results every time.", "3-day quality window": "If anything's not right, you have three full days to let us know and we'll fix it before you're ever charged.", "Cancel anytime": "You can cancel up to 48 hours before any scheduled service — no fees, no hassle."}, "closes": {"Soft": "Would it help if I saved you a spot on the schedule? No commitment until after the service is done.", "Assumptive": "Let's go ahead and get you set up — what address are we working with?", "Question": "What's the main thing still holding you back?"}},
    "Price Concern": {"openings": {"Empathetic": "I completely understand — price is always a factor, and I want to make sure you're getting real value.", "Curious": "Totally fair. When you say the price feels high, are you comparing to another quote or just what you expected?", "Direct": "Let me tell you exactly what you're getting for that price, because I think it's actually a great deal."}, "points": {"Insured professionals": "Every pro on our platform is verified and insured. You're not gambling on some random person showing up.", "Quality guarantee": "You have a full three days to inspect the work before you're charged. If anything's off, we fix it first.", "Dedicated support team": "We have a whole team whose only job is making sure you're happy with the service.", "No surprise charges": "The price you see is the price you pay — we're upfront about everything, including any potential fees.", "Compare apples to apples": "Make sure you're comparing the full package — insurance, support, and our quality guarantee included."}, "closes": {"Soft": "How about this — let's get you on the schedule and you can see the quality for yourself. You won't pay until three days after.", "Assumptive": "I think once you see the quality, the price will make total sense. Let's get you on the schedule.", "Question": "If the quality matches what I'm telling you, would that price feel fair?"}},
    "Timing / Need It Today": {"openings": {"Empathetic": "I totally get it — when you need it done, you need it done. Let me see what we can do.", "Curious": "Sounds urgent! What's going on — got an event coming up or just hit that breaking point with the yard?", "Direct": "So here's the deal — we have a 48-hour turnaround, but let me tell you why that's actually still the fastest around."}, "points": {"Fastest in industry": "48 hours is actually the fastest turnaround in the industry. We price before we arrive, so there's no waiting around.", "Message your crew": "After signup, you can message your crew directly through the app and ask if they can squeeze you in sooner. Worth a shot!", "HOA email": "If you've got an HOA breathing down your neck, we can send you a confirmation email right away that you can forward to them.", "Lock in your spot": "If you grab a spot now, you're guaranteed on the schedule. Wait, and availability might fill up.", "Free cancellation": "You can cancel up to 48 hours before if your situation changes — no penalty."}, "closes": {"Soft": "Want me to lock in the earliest available slot? You can always message the crew to see if they can come sooner.", "Assumptive": "Let's get you scheduled for the first available — what's the address?", "Question": "If we can get you in within 48 hours, does that work for your timeline?"}},
    "Shopping Around": {"openings": {"Empathetic": "That makes total sense — it's smart to know your options before deciding.", "Curious": "Totally fair! Have you already talked to other companies, or are you just starting to look around?", "Direct": "I'd love the chance to show you why we stand out. Can I ask what's most important to you in a lawn service?"}, "points": {"Compare protection": "Make sure whoever you go with is insured. If they damage something or don't show, you want to be covered.", "Our reviews": "If you Google us, you'll see we have amazing reviews. People love working with us.", "No risk to try": "You don't pay until three days after service, so you can literally see the quality before any money changes hands.", "Hold your spot": "I can save a spot on the schedule for you while you decide — no commitment, no charge until after service.", "Easy cancellation": "Even after you book, you can cancel up to 48 hours before if you find someone else. Zero pressure."}, "closes": {"Soft": "How about I hold a spot for you? No commitment — just keeps your options open while you decide.", "Assumptive": "Let's get you on the schedule. If you find someone better, you can cancel anytime before 48 hours out.", "Question": "What would you need to see from us to feel confident going with us over someone else?"}},
    "Payment Method": {"openings": {"Empathetic": "I get it — a lot of people ask about that. Let me explain why we do it this way.", "Curious": "Totally fair question! Is there a specific concern with using a card, or is it just preference?", "Direct": "We only accept major credit or debit cards, but here's why that's actually a good thing for you."}, "points": {"Bank protection": "With a card, your bank has your back. If anything ever went wrong, you've got that extra layer of protection.", "Crews get paid": "It also means our crews know they're guaranteed payment, so they show up ready to do great work.", "No upfront charge": "Remember, we don't charge until three days after the service — so your card isn't hit until you've seen the work.", "Secure system": "Your card info is stored securely. We take that seriously.", "Industry standard": "Most professional services work this way now. It protects everyone involved."}, "closes": {"Soft": "Does that make sense? I promise it's set up to protect you, not complicate things.", "Assumptive": "Let's get you set up — I just need a card on file and we're good to go.", "Question": "If you knew you wouldn't be charged until three days after and could dispute anything with your bank, would that feel okay?"}},
    "Fees (Long Grass Fee)": {"openings": {"Empathetic": "I totally get the concern — nobody likes surprise fees. Let me explain exactly how this works.", "Curious": "Great question! Do you have a sense of how tall your grass is right now?", "Direct": "So I want to be upfront with you about this — that's actually why I'm mentioning it now."}, "points": {"Transparency": "We're telling you NOW so there are no surprises later. That's the whole reason we bring it up.", "Industry standard": "This is actually standard across the industry — overgrown yards take more time and wear on equipment.", "9 inch threshold": "It only applies if the grass is 9 inches or taller. If your lawn is maintained, it won't apply at all.", "Up to 100% of base": "If it does apply, it can be up to 100% of your base mowing price — but only when it's really overgrown.", "One-time situation": "Usually this only comes up on the first cut if it's been a while. After that, regular service keeps it under control."}, "closes": {"Soft": "Does that make sense? We just want to be transparent so you know exactly what to expect.", "Assumptive": "Now that you know how it works, let's get you on the schedule. What's the address?", "Question": "Does your lawn sound like it might be in that range, or do you think you're under 9 inches?"}},
    "Trust / Never Heard of You": {"openings": {"Empathetic": "That's totally fair — I'd want to know who I'm working with too.", "Curious": "Totally understand! What would help you feel more comfortable giving us a shot?", "Direct": "Let me tell you a bit about us and why so many people trust us with their lawns."}, "points": {"Amazing reviews": "If you Google us, you'll see we have amazing reviews. Real people, real experiences.", "All pros insured": "Every single pro on our platform is verified and insured. We don't let just anyone on here.", "Quality guarantee": "You have three full days after service to inspect the work before you're charged.", "Dedicated quality team": "We have a whole team whose only job is making things right if anything's ever off.", "No payment until satisfied": "You don't pay until three days after the service, so you see the quality before any money changes hands.", "Fix before you pay": "If there's any issue, we send someone to fix it BEFORE you're ever charged."}, "closes": {"Soft": "How about you check out our reviews and let me save you a spot in the meantime? No pressure.", "Assumptive": "I think once you see the quality, you'll be glad you went with us. Let's get you scheduled.", "Question": "What would make you feel confident enough to give us a shot?"}}
}

attach_guides = {
    "Lawn Treatment": {"triggers": ["Weeds everywhere", "Grass is turning brown", "Neighbor's lawn looks better", "Lawn looks thin/patchy", "Weeds keep coming back", "Yellow spots"], "openings": {"Empathetic": "I hear that a lot — dealing with weeds and patchy grass can be really frustrating, especially when you feel like you've tried everything.", "Curious": "Have you noticed if it's more weeds, or is the grass itself looking thin and unhealthy? Just trying to get a picture of what you're dealing with.", "Direct": "Sounds like your lawn could really benefit from our lawn treatment program — let me tell you what it includes."}, "points": {"Fertilizer for green-up": "It includes fertilizer that helps thicken up your grass and get that green color back.", "Pre-emergent stops new weeds": "There's a pre-emergent that stops weeds before they even start — so you're not constantly fighting new ones.", "Post-emergent kills existing weeds": "It also has post-emergent to knock out the weeds that are already there.", "Results in weeks": "Most people see a real difference within just a few weeks.", "Pro learns your lawn": "And since the same pro comes back, they get to know your lawn and what it needs over time."}, "closes": {"Soft": "Want me to add that on so we can start getting your lawn back in shape?", "Assumptive": "Let's go ahead and add the lawn treatment — that way we're tackling the root of the problem, not just mowing over it.", "Question": "Would it help to get the lawn treatment started at the same time so you're not dealing with two separate things?"}, "pro_tip": "If they mention weeds, ask if they've noticed them in specific areas or all over. This helps you explain how the pre-emergent prevents new ones while post-emergent handles what's already there."},
    "Leaf Removal": {"triggers": ["Leaves are piling up", "Yard is covered in leaves", "Can't even see my grass", "Fall cleanup", "Leaves are out of control"], "openings": {"Empathetic": "Yeah, this time of year it feels like you clean them up and they're right back the next day. It's a lot to keep up with.", "Curious": "How bad has it gotten? Are we talking a light layer or is the grass completely buried at this point?", "Direct": "We actually offer leaf removal too — and it's worth doing sooner rather than later."}, "points": {"Protects your lawn": "Leaves left too long can actually suffocate your grass and cause dead patches underneath.", "Instant curb appeal": "Once they're cleared out, your whole yard looks cleaner and more cared for right away.", "Saves you time": "It's one of those jobs that takes forever to do yourself but our crew can knock it out quickly.", "Prevents mold and pests": "Wet leaves can also lead to mold and attract pests, so it's good to get ahead of it.", "One crew handles it": "We can do it the same time as your mow so you're not scheduling multiple visits."}, "closes": {"Soft": "Want me to add leaf removal to this visit so we can get that taken care of for you?", "Assumptive": "Let's add the leaf removal too — no point mowing over leaves, and it'll protect your grass going into winter.", "Question": "Would it be easier if we just handled the leaves while we're already there?"}, "pro_tip": "Mention the lawn health angle — most people don't realize leaves can actually damage grass if left too long. It turns the conversation from 'extra service' to 'protecting your lawn.'"},
    "Bush Trimming": {"triggers": ["Bushes are overgrown", "Shrubs are out of control", "Everything looks messy", "Curb appeal", "Getting ready to sell", "HOA notice about bushes"], "openings": {"Empathetic": "Overgrown bushes can really make the whole yard feel messy, even when the lawn itself looks good. I totally get it.", "Curious": "How long has it been since they were last trimmed? Sometimes they just need a good reset to look sharp again.", "Direct": "We do bush trimming too, and honestly it's one of the fastest ways to boost your curb appeal."}, "points": {"Instant curb appeal": "Trimmed bushes make a huge difference in how the whole property looks from the street.", "Keeps bushes healthy": "Regular trimming actually keeps them healthier and growing the right way.", "HOA compliant": "If you've got an HOA, this keeps you in compliance so you don't have to worry about notices.", "Frames the home nicely": "Well-maintained bushes frame your home and make everything look more polished.", "Same visit convenience": "We can do it during the same visit as your mow, so it's one less thing to coordinate."}, "closes": {"Soft": "Want me to add bush trimming so we can get everything looking sharp at once?", "Assumptive": "Let's add the bush trimming — it'll really complete the look and you won't have to think about it.", "Question": "Would it help to have us handle the bushes while we're already out there?"}, "pro_tip": "If they mention selling their home or HOA issues, lean into urgency — trimmed bushes are one of the fastest ways to boost curb appeal, and it's often the first thing buyers and HOAs notice."},
    "Flower Bed Weeding": {"triggers": ["Flower beds are a mess", "Weeds in my beds", "Can't even see my flowers", "Landscaping looks rough", "Beds are overgrown"], "openings": {"Empathetic": "Flower beds can get out of hand so fast — one week they're fine, the next week weeds have taken over. It's a lot to maintain.", "Curious": "Are the weeds the main issue, or is it more just general cleanup and overgrowth in the beds?", "Direct": "We do flower bed weeding too, and honestly it's one of those things that makes a huge visual difference."}, "points": {"Shows off your plants": "Once the weeds are out, your actual flowers and plants can finally shine.", "Polished look": "Clean beds make the whole property look more cared for and put-together.", "Finishing touch": "Even a freshly mowed lawn can look incomplete if the beds are messy — this is the finishing touch.", "Low maintenance after": "Once we get them cleaned up, it's way easier to maintain going forward.", "Boosts curb appeal": "It's one of the first things people notice when they pull up to a house."}, "closes": {"Soft": "Want me to add flower bed weeding so we can get the whole yard looking great?", "Assumptive": "Let's add the bed weeding — it'll really pull everything together and make the whole property pop.", "Question": "Would it make sense to have us tackle the beds while we're already there?"}, "pro_tip": "Use the 'finishing touch' angle — even a freshly mowed lawn can look incomplete if the beds are messy. Frame it as the difference between 'good' and 'wow.'"},
    "Full Curb Appeal Bundle": {"triggers": ["Getting ready to sell", "Want the whole yard done", "Just moved in", "Event coming up", "Family visiting", "Make it look brand new"], "openings": {"Empathetic": "When you're prepping for something big, the last thing you want is to stress about the yard. I totally get wanting it all handled at once.", "Curious": "What's the occasion? Just want to make sure we set you up with everything you need to get it looking perfect.", "Direct": "If you're going for a full transformation, we can bundle everything together and really make the whole property pop."}, "points": {"Complete transformation": "We can do mowing, bush trimming, flower bed weeding, and leaf removal if needed — the whole package.", "One crew handles it all": "Instead of coordinating multiple services, one crew takes care of everything in one visit.", "Saves time and stress": "You don't have to think about it or manage different appointments — we've got it covered.", "Perfect for selling": "If you're selling, this is exactly what gets buyers to say 'wow' when they pull up.", "Great for events": "If you've got family coming or an event, this is the fastest way to get the yard guest-ready."}, "closes": {"Soft": "Want me to put together the full bundle so you don't have to worry about any of it?", "Assumptive": "Let's do the full curb appeal package — that way you're covered and the whole property will look amazing.", "Question": "Would it be easier to just bundle it all and knock it out in one visit?"}, "pro_tip": "When someone has a big event or is selling, they're already in 'get it done' mode. Don't be shy about suggesting the full bundle — they'll appreciate you making it easy."}
}

upsell_pathways = {
    "Lawn Mowing": {"icon": "🏡", "desc": "Customer called about mowing service", "paths": {
        "Lawn Treatment": {"icon": "🧪", "strength": "Strong", "listen_for": ["My yard is full of weeds", "Grass is turning brown / yellow", "Neighbor's lawn looks way better", "Lawn looks thin or patchy", "Weeds keep coming back no matter what"], "bridge": "You know, mowing keeps things neat — but if weeds or brown patches are the real issue, that's actually a lawn health problem. We have a treatment program that tackles that at the root.", "why_it_works": "Mowing customers already care about how their lawn looks. Treatment solves the problems mowing alone can't fix.", "key_points": ["Fertilizer thickens grass and restores color", "Pre-emergent stops new weeds before they start", "Post-emergent kills weeds already there", "Fewer weeds = less overgrowth = potentially lower mowing costs", "Same pro learns their lawn over time"], "transition_line": "Since we're already going to be out there mowing, it's a perfect time to start the treatment too — knocks out two things in one visit."},
        "Leaf Removal": {"icon": "🍂", "strength": "Seasonal", "listen_for": ["Leaves are everywhere", "Can't even see my grass anymore", "It's that time of year", "My yard is a mess with all the leaves", "I've been raking but can't keep up"], "bridge": "Before we mow, I do want to ask — are there leaves or debris on the lawn right now? If there's a heavy layer, that can actually affect the mow quality.", "why_it_works": "Natural lead-in because excessive leaves literally impact the mowing service.", "key_points": ["Leaves left too long suffocate grass and cause dead patches", "Crew can handle it during the same visit", "If they show up and leaves are excessive, they'd need to quote cleanup anyway", "Instant curb appeal boost", "Prevents mold and pest issues"], "transition_line": "We can bundle the leaf removal with your mow so it's all handled in one shot."},
        "Bush Trimming": {"icon": "✂️", "strength": "Moderate", "listen_for": ["Everything looks overgrown", "I want the whole yard to look nice", "Getting ready to sell / have guests", "HOA mentioned my bushes too", "Bushes are out of control"], "bridge": "Once the lawn is looking sharp, the bushes can sometimes stand out if they're overgrown. A lot of people add bush trimming to really complete the look.", "why_it_works": "A freshly mowed lawn next to overgrown bushes creates contrast that makes the bushes look worse.", "key_points": ["Trimmed bushes frame the home and boost curb appeal", "Regular trimming keeps bushes healthy", "Same visit convenience — one crew handles it all", "Keeps HOA happy", "The contrast between a clean lawn and messy bushes is noticeable"], "transition_line": "While the crew's already there, they can knock out the bushes too — really makes the whole property pop."},
        "Flower Bed Weeding": {"icon": "🌺", "strength": "Moderate", "listen_for": ["My flower beds are a mess", "Weeds everywhere, not just the lawn", "I want it to look really polished", "Can't even see my flowers anymore", "The beds look rough"], "bridge": "One thing I always mention — even a perfectly mowed lawn can look incomplete if the flower beds are overrun. It's like the finishing touch.", "why_it_works": "Positions bed weeding as the difference between 'good' and 'wow.'", "key_points": ["Clean beds make the whole property look more cared for", "Shows off the actual flowers and plants", "Once cleaned up, much easier to maintain going forward", "One of the first things people notice from the curb", "Can be done during the same visit"], "transition_line": "If you want the yard to really look complete, adding bed weeding takes it from 'nice lawn' to 'wow, that whole yard looks amazing.'"}}},
    "Lawn Treatment": {"icon": "🧪", "desc": "Customer called about fertilizer / weed control", "paths": {
        "Lawn Mowing": {"icon": "🏡", "strength": "Strong", "listen_for": ["I don't have anyone mowing right now", "I've been doing it myself", "My current mower isn't great", "I hate mowing", "Who's going to maintain it between treatments?"], "bridge": "So the treatment will get your lawn healthy and thick — but between applications, you'll want consistent mowing to keep it looking sharp. Do you have someone handling that?", "why_it_works": "Treatment without mowing is incomplete. The lawn will grow faster and healthier with treatment.", "key_points": ["Treatment makes grass grow thicker and faster — needs regular mowing", "Same pro can learn the lawn and maintain it properly", "Mowing, edging, and blowing all included", "3-day quality check before you're charged", "Flexible scheduling — weekly, biweekly, or monthly"], "transition_line": "Since the treatment is going to really boost your lawn's growth, let's get mowing set up too."},
        "Flower Bed Weeding": {"icon": "🌺", "strength": "Strong", "listen_for": ["The weeds aren't just in the lawn", "My beds are a mess too", "I want to get everything cleaned up", "Weeds are taking over the whole yard", "What about weeds in my flower beds?"], "bridge": "The treatment handles the lawn weeds, but it won't touch what's in your flower beds. If those are looking rough too, we can take care of that separately.", "why_it_works": "Customer is already in 'weed-fighting mode.' Easy to extend that mindset to the beds.", "key_points": ["Lawn treatment only covers the grass — beds need separate attention", "Clean beds complement a treated lawn perfectly", "Once cleared out, easier to maintain", "Boosts overall curb appeal", "Can be done during the same visit window"], "transition_line": "Since we're already fighting weeds in the lawn, let's knock out the beds too."},
        "Bush Trimming": {"icon": "✂️", "strength": "Moderate", "listen_for": ["I want the whole yard to look good", "Getting the property in shape", "What else do you offer?", "The bushes need work too", "Trying to get curb appeal up"], "bridge": "If you're investing in lawn health, it's worth making sure the rest of the yard matches.", "why_it_works": "Customer is already investing in the yard. Bush trimming completes the picture.", "key_points": ["Protects the curb appeal investment they're already making", "Trimmed bushes frame the home nicely", "Same visit convenience", "Regular trimming keeps bushes healthy long-term", "One less thing to worry about"], "transition_line": "Let's add bush trimming so the whole yard matches the lawn once it starts looking amazing."}}},
    "Leaf Removal": {"icon": "🍂", "desc": "Customer called about leaf cleanup", "paths": {
        "Lawn Mowing": {"icon": "🏡", "strength": "Strong", "listen_for": ["The lawn's gotten out of hand", "Haven't been able to keep up with anything", "Need someone to maintain the yard", "It's not just the leaves — everything's a mess", "I need regular help going forward"], "bridge": "Once the leaves are cleared, you'll probably want to keep the lawn looking good going forward. Do you have someone handling the regular mowing?", "why_it_works": "Leaf removal is often a 'breaking point' call — they've fallen behind and need help.", "key_points": ["Once leaves are cleared, regular mowing keeps it maintained", "3-cut minimum is flexible — use whenever you need", "Don't pay until 3 days after service", "Crew already knows the property from the leaf job", "Prevents falling behind again"], "transition_line": "Since the crew will already be out there and know your property, it's a great time to get on a regular mowing schedule too."},
        "Lawn Treatment": {"icon": "🧪", "strength": "Moderate", "listen_for": ["The lawn looks dead under the leaves", "I'm worried about the grass", "Will my lawn recover?", "Grass looks brown and thin", "Leaves have been sitting there for weeks"], "bridge": "Leaves sitting on the lawn can actually damage the grass underneath — you might notice some thin or brown spots once they're cleared.", "why_it_works": "Connects the leaf problem to potential lawn damage, which treatment solves.", "key_points": ["Leaves suffocate grass and can cause dead patches", "Fertilizer helps grass recover and thicken up", "Pre-emergent prevents weeds from filling in bare spots", "Treatment + removal = complete recovery plan", "Results visible within a few weeks"], "transition_line": "Once the leaves are off, let's get the treatment started so the grass can recover."},
        "Bush Trimming": {"icon": "✂️", "strength": "Moderate", "listen_for": ["The whole yard is a mess", "I just want everything cleaned up", "It's been neglected for a while", "Getting ready for an event / selling", "What else can you do while you're here?"], "bridge": "If we're doing a full cleanup with the leaves, it might be a good time to get the bushes trimmed too.", "why_it_works": "Customer is already in cleanup mode. Adding bush trimming turns a single service into a full transformation.", "key_points": ["Full cleanup + trimming = complete yard transformation", "One visit handles everything", "Huge curb appeal boost all at once", "Saves time coordinating multiple visits later", "If selling or hosting, this is the fastest path to 'wow'"], "transition_line": "Let's make it a full transformation — leaves cleared, bushes trimmed, whole property looking sharp."}}},
    "Bush Trimming": {"icon": "✂️", "desc": "Customer called about bush/shrub trimming", "paths": {
        "Lawn Mowing": {"icon": "🏡", "strength": "Strong", "listen_for": ["The lawn needs work too", "I want the whole yard done", "Don't have a mowing service right now", "Everything's overgrown", "Getting the property in order"], "bridge": "Trimmed bushes will look amazing, but they'll really stand out against a well-maintained lawn. Do you have someone handling the mowing?", "why_it_works": "Trimmed bushes next to an unkempt lawn looks odd. Reps can paint the full picture.", "key_points": ["Trimmed bushes + maintained lawn = complete curb appeal", "Crew is already on site and knows the property", "Flexible 3-cut minimum with no upfront payment", "3-day quality check on every service", "One company handles everything"], "transition_line": "While the crew is there for the bushes, let's get the lawn on a regular schedule too."},
        "Flower Bed Weeding": {"icon": "🌺", "strength": "Strong", "listen_for": ["The beds around the bushes are messy", "Weeds are growing up around everything", "I want it all cleaned up", "The area around the bushes looks bad", "Can you do the beds too?"], "bridge": "When we're trimming the bushes, we'll probably notice if the beds around them need attention. Want us to handle the weeding at the same time?", "why_it_works": "Bushes and flower beds are usually right next to each other.", "key_points": ["Bushes and beds are right next to each other — do both for the full effect", "Clean beds make the fresh trim look even better", "One visit, one crew, everything handled", "Shows off your landscaping properly", "The finishing touch that ties it all together"], "transition_line": "Since the crew's already working right around the beds, let's have them weed those too."},
        "Lawn Treatment": {"icon": "🧪", "strength": "Light", "listen_for": ["My lawn doesn't look great either", "Weeds are taking over the grass too", "I want the whole property to look nice", "The grass is thin / brown", "Any way to improve the actual lawn?"], "bridge": "If the lawn itself isn't looking its best, we have a treatment program that can really transform it.", "why_it_works": "Lighter connection, but works when the customer is in 'whole property improvement' mode.", "key_points": ["Treatment tackles lawn health — thickness, color, weeds", "Complements the polished look from trimmed bushes", "Results in just a few weeks", "7-8 rounds per year keeps it looking great year-round", "Fewer weeds = less overgrowth overall"], "transition_line": "If you want the lawn to match how great the bushes will look, the treatment program is the way to go."}}},
    "Flower Bed Weeding": {"icon": "🌺", "desc": "Customer called about flower bed maintenance", "paths": {
        "Lawn Mowing": {"icon": "🏡", "strength": "Strong", "listen_for": ["The lawn needs help too", "I want the whole yard looking good", "Everything's gotten away from me", "Don't have a regular service", "Just moved in and need everything done"], "bridge": "Clean beds are going to look great — but they'll really shine when the lawn around them is maintained too. Do you have mowing set up?", "why_it_works": "Clean beds next to an unkempt lawn doesn't complete the look.", "key_points": ["Clean beds + maintained lawn = polished property", "Crew already knows the property layout", "Flexible scheduling with no upfront payment", "3-day quality guarantee on every service", "One point of contact for everything"], "transition_line": "Let's get the mowing going too so the whole yard matches those clean beds."},
        "Bush Trimming": {"icon": "✂️", "strength": "Strong", "listen_for": ["The bushes next to the beds are overgrown too", "Everything in the front looks messy", "I want the landscaping to look nice", "The bushes are growing into the beds", "Can you trim while you're at it?"], "bridge": "If the bushes near the beds are overgrown too, we can trim those at the same time.", "why_it_works": "Bushes and beds live in the same space. Cleaning one without the other is only half the job.", "key_points": ["Bushes and beds together create the landscaping look", "Overgrown bushes can shade out flowers and plants", "One visit handles both", "Huge curb appeal impact", "Keeps everything proportional and tidy"], "transition_line": "Let's do both — beds weeded and bushes trimmed. That's going to completely transform the front of the house."},
        "Lawn Treatment": {"icon": "🧪", "strength": "Moderate", "listen_for": ["Weeds are everywhere, not just the beds", "The lawn has weeds too", "I want to stop the weed problem", "Grass looks bad around the beds", "Is there something for the lawn weeds?"], "bridge": "If weeds are an issue in the beds AND the lawn, our treatment program can handle the lawn side.", "why_it_works": "Customer already has a weed problem mindset. Treatment extends the solution to the whole yard.", "key_points": ["Tackles weeds at the source across the whole lawn", "Pre-emergent prevents new weeds from spreading into beds", "Healthier lawn = less weed migration into beds", "Comprehensive approach to the weed problem", "Results visible in weeks"], "transition_line": "Since weeds are the main issue, let's hit them from both sides — bed weeding for the beds, treatment for the lawn."}}}
}

disposition_guide = {
    "Already Hired A Provider": {"category": "Customer Not Interested", "icon": "🏢", "short": "Customer already has another lawn service provider.", "when": "The customer tells you they've already signed up with or hired someone else.", "examples": ["I just signed up with another lawn service yesterday.", "I already have a guy who does my lawn.", "We went with a different company last week."], "not_this": ["If they're comparing quotes but haven't committed → Keep selling", "If they had a provider but are looking to switch → This is a lead, not a loss"], "confused_with": ["Not Qualified - Refuse Contact"]},
    "Arrival Time": {"category": "Scheduling Issue", "icon": "⏰", "short": "Customer requires a specific time of day for service.", "when": "The customer insists on a particular arrival time that we can't guarantee due to our two-day service window.", "examples": ["Can you come at exactly 3 PM on Friday?", "I need the crew here before 9 AM.", "It has to be done in the afternoon only."], "not_this": ["If they need it within 48 hours → Less Than 48 Hour Turn-Around", "If they're flexible on time but want specific days → Keep selling"], "confused_with": ["Less Than 48 Hour Turn-Around"]},
    "Broken Address": {"category": "System / Technical", "icon": "📍", "short": "System can't generate a price — address isn't recognized.", "when": "You enter the address and the system doesn't recognize it — usually new construction or new development.", "examples": ["The system can't find your address.", "It's a brand new build.", "My street doesn't show up in your system."], "not_this": ["If the address IS recognized but outside our area → Out Of Area", "If the customer gave the wrong address → Junk Contact"], "confused_with": ["Out Of Area"]},
    "Callback": {"category": "Follow-Up Needed", "icon": "📞", "short": "Customer is interested but wants a callback at a specific later date.", "when": "They're interested but not ready NOW — they give you a specific time or date to call back.", "examples": ["Can you call me back next month?", "I'm interested but not until after I move in.", "Let me think about it, try me again Friday."], "not_this": ["If they're rushed and you can't qualify → Timing - Unable to Qualify", "If they say 'call me next spring' → Still use Callback, note the timeframe", "If they say 'don't call me again' → Not Qualified - Refuse Contact"], "confused_with": ["Timing - Unable to Qualify", "Next Spring"]},
    "Dead Air": {"category": "No Contact Made", "icon": "🔇", "short": "Call connects but nobody responds — complete silence.", "when": "The call connects (not voicemail) but there's complete silence. You've repeated your opening at least twice with no response.", "examples": ["Hello? Is anyone there? (silence)"], "not_this": ["If the call cuts off mid-conversation → Disconnected", "If you reach voicemail → Drop Voicemail"], "confused_with": ["Disconnected", "Drop Voicemail"]},
    "Disconnected": {"category": "No Contact Made", "icon": "📵", "short": "Call drops mid-conversation. Triggers auto-callback in 1 min.", "when": "You WERE talking to someone and the call suddenly drops. Note: this triggers an auto-callback within 1 minute.", "examples": ["We were discussing the 3-cut minimum and the line went dead.", "Customer was mid-sentence and the call dropped."], "not_this": ["If nobody ever responded → Dead Air", "If they intentionally hung up after saying no → Not Qualified - Refuse Contact"], "confused_with": ["Dead Air"]},
    "Drop Voicemail": {"category": "No Contact Made", "icon": "📧", "short": "Reached voicemail — system auto-drops a message.", "when": "You call and get their voicemail. Selecting this auto-drops a voicemail — no need to leave one manually.", "examples": ["Went straight to voicemail.", "Rang several times, then voicemail picked up."], "not_this": ["If the call connects to a live person with silence → Dead Air", "If someone answers but it's the wrong number → Junk Contact"], "confused_with": ["Dead Air"]},
    "Duplicate": {"category": "System / Technical", "icon": "👥", "short": "Customer already signed up or spoke with another agent.", "when": "They tell you they've already spoken with an agent, already got a quote from us, or already completed signup.", "examples": ["I already spoke with someone about this.", "I signed up online yesterday.", "I already have a quote from you guys."], "not_this": ["If they signed up with a DIFFERENT company → Already Hired A Provider", "If they're an existing customer needing help → Support Call"], "confused_with": ["Already Hired A Provider", "Support Call"]},
    "Frequency Minimum": {"category": "Service Objection", "icon": "📅", "short": "Customer wants service LESS often than monthly.", "when": "They want to mow less often than monthly — like 'just call when I need it' or 'every 6 weeks.'", "examples": ["I only want it mowed every 6 weeks.", "Can I just call when I need it?", "Monthly is too often for me."], "not_this": ["If they object to the 3-cut minimum (number of cuts) → Minimum Cuts Requirement"], "confused_with": ["Minimum Cuts Requirement"]},
    "Insufficient Capacity": {"category": "System / Technical", "icon": "🚫", "short": "We service their area but have NO available crews right now.", "when": "The system generates a price but the calendar shows ALL red days — no availability.", "examples": ["Calendar is completely red — no open slots."], "not_this": ["If the system can't generate a price at all → Out Of Area or Broken Address", "If there IS availability but not within 48 hours → Less Than 48 Hour Turn-Around"], "confused_with": ["Out Of Area"]},
    "Junk Contact": {"category": "Invalid Lead", "icon": "🗑️", "short": "Wrong number, wrong address, wrong branding, or job applicant.", "when": "Wrong number, incorrect address, wrong brand used, or caller asking about a job application.", "examples": ["You've called the wrong number.", "I never requested lawn service.", "I'm calling about my job application."], "not_this": ["If it's a telemarketer calling us → Not Qualified - Telemarketer", "If the address doesn't work in the system → Broken Address"], "confused_with": ["Not Qualified - Telemarketer", "Broken Address"]},
    "Less Than 48 Hour Turn-Around": {"category": "Scheduling Issue", "icon": "⚡", "short": "Customer needs service within 48 hours and won't wait.", "when": "They need it TODAY or TOMORROW and refuse to wait, even after you've tried to handle the objection.", "examples": ["I need it done today, no exceptions.", "I can't wait 48 hours.", "If you can't come today, I'll find someone else."], "not_this": ["If they want a specific TIME of day → Arrival Time", "If they're open to waiting after you explain → Keep selling!"], "confused_with": ["Arrival Time"]},
    "LGF - Long Grass Fee": {"category": "Service Objection", "icon": "🌿", "short": "Customer refuses the long grass fee.", "when": "You've explained the fee and they flat-out refuse to proceed because of it.", "examples": ["I don't want to pay extra for long grass.", "That fee is ridiculous.", "No way I'm paying double."], "not_this": ["If they have questions but are still open → Handle the objection", "If their concern is overall price → Price"], "confused_with": ["Price"]},
    "Minimum Cuts Requirement": {"category": "Service Objection", "icon": "3️⃣", "short": "Customer refuses the 3-cut minimum commitment.", "when": "They only want 1 or 2 cuts and won't agree to 3 after you've tried the objection.", "examples": ["I only want two cuts.", "I just need one mow — that's it.", "Three cuts is too many."], "not_this": ["If they want service less often than monthly → Frequency Minimum", "If they say 'one-time' but you haven't tried to overcome it → Try first!"], "confused_with": ["Frequency Minimum"]},
    "No In-Person Quote": {"category": "Service Objection", "icon": "👀", "short": "Customer insists on an in-person walkthrough before getting a quote.", "when": "They want someone to physically come to their property before they'll consider a price.", "examples": ["Can someone come look at my yard first?", "I won't agree without someone seeing it in person."], "not_this": ["If they just want to know how we price → Explain satellite pricing", "If the property is too complex → Order Complexity"], "confused_with": ["Order Complexity"]},
    "Not DM": {"category": "Decision Maker Issue", "icon": "🙋", "short": "Person on the call isn't the decision maker.", "when": "They're gathering info for a spouse, parent, roommate, boss, or homeowner. You MUST offer to hold a spot.", "examples": ["I'm just gathering information for my husband.", "My mom owns the house.", "Let me check with my wife first."], "not_this": ["If they say 'talk to spouse' as a stall → Try the objection first", "If they say 'stop calling' → Not Qualified - Refuse Contact"], "confused_with": ["Not Qualified - Refuse Contact", "Callback"]},
    "Timing - Unable to Qualify": {"category": "Follow-Up Needed", "icon": "⏳", "short": "Customer is in a rush — can't properly qualify them.", "when": "They don't have time for the full process. Always ask about a callback first (if yes → use Callback).", "examples": ["I'm in a hurry, just give me a price.", "I only have 30 seconds.", "I gotta go."], "not_this": ["If they agree to a callback → Callback", "If they had time but aren't interested → Not Qualified - Refuse Contact"], "confused_with": ["Callback", "Less Than 48 Hour Turn-Around"]},
    "Not Qualified - Refuse Contact": {"category": "Customer Not Interested", "icon": "🚫", "short": "Customer says don't contact them again.", "when": "They clearly say stop calling, take them off the list, or refuse any further discussion.", "examples": ["Please take me off your list.", "Don't call me again.", "I'm not interested — stop calling."], "not_this": ["If they're just not interested RIGHT NOW → Callback", "If they already have a provider → Already Hired A Provider"], "confused_with": ["Already Hired A Provider", "Junk Contact"]},
    "Not Qualified - Telemarketer": {"category": "Invalid Lead", "icon": "📢", "short": "The caller is trying to sell US something.", "when": "Caller is a telemarketer, pitching sponsorships, or selling products/services.", "examples": ["I'm looking to speak to the owner about a sponsorship.", "We offer marketing services for lawn companies."], "not_this": ["If they want to become a provider for us → Provider Inquiry", "If it's a wrong number → Junk Contact"], "confused_with": ["Provider Inquiry", "Junk Contact"]},
    "Order Complexity": {"category": "System / Technical", "icon": "🔧", "short": "Too complex — can't use app, no email, needs home access, or flagged account.", "when": "They can't use the app, don't have email, find the system too difficult, need crew to enter through their home, or account is flagged.", "examples": ["I can't figure out how to use your app.", "I don't have an email address.", "The crew would need to go through my garage."], "not_this": ["If the system can't find their address → Broken Address", "If they want an in-person quote → No In-Person Quote"], "confused_with": ["Broken Address", "No In-Person Quote"]},
    "Out Of Area": {"category": "System / Technical", "icon": "🗺️", "short": "Customer's address is outside our service area.", "when": "Calendar shows all red days AND no pricing available — we don't service their area.", "examples": ["I'm in a neighboring town; do you service here?"], "not_this": ["If system gives a price but no availability → Insufficient Capacity", "If the address isn't recognized → Broken Address"], "confused_with": ["Insufficient Capacity", "Broken Address"]},
    "Oversized Lot": {"category": "Property Issue", "icon": "🏞️", "short": "Property exceeds 160,000 sq ft / 3.67 acres.", "when": "The lot is bigger than our max of 160,000 sq ft or 3.67 acres.", "examples": ["My property is over four acres.", "I have a 5-acre lot."], "not_this": ["If the property is large but under 160k sq ft → Normal order"], "confused_with": ["Services Not Offered"]},
    "Pre Paid Card": {"category": "Payment Issue", "icon": "💳", "short": "Customer only has a prepaid card, or their card was declined.", "when": "They only have a prepaid card, or their credit/debit card gets declined.", "examples": ["I'd like to pay with my prepaid card.", "My card keeps getting declined."], "not_this": ["If they refuse to put ANY card on file → Rejected CC"], "confused_with": ["Rejected CC"]},
    "Price": {"category": "Service Objection", "icon": "💰", "short": "Overall price is too high for their budget.", "when": "They can't afford or don't want to pay our price — budget or value concern.", "examples": ["Your services are too expensive.", "That's way more than I expected.", "I can't afford that."], "not_this": ["If they're objecting to the LONG GRASS fee specifically → LGF", "If they say it's expensive but are still listening → Handle the objection!"], "confused_with": ["LGF - Long Grass Fee"]},
    "Property Manager": {"category": "Special Caller", "icon": "🏘️", "short": "Property manager / realtor calling about a client's property — couldn't close.", "when": "Caller manages properties for someone else. Always use this for property managers regardless of the objection.", "examples": ["I'm managing a client's property.", "I'm a realtor needing service for a listing."], "not_this": ["If it's a regular homeowner → Use their specific objection disposition"], "confused_with": ["Services Not Offered"]},
    "Provider Inquiry": {"category": "Special Caller", "icon": "🤝", "short": "Caller wants to become a service provider / join our network.", "when": "They want to work FOR us, not hire us.", "examples": ["How can I become a provider?", "I have a lawn care business and want to partner."], "not_this": ["If they're trying to sell us something → Not Qualified - Telemarketer"], "confused_with": ["Not Qualified - Telemarketer"]},
    "Rejected CC": {"category": "Payment Issue", "icon": "💵", "short": "Customer refuses to put any card on file — wants cash or check.", "when": "They flat-out refuse to provide any card and insist on cash, check, or other methods.", "examples": ["I'd rather pay with cash.", "I'm not putting my card on file.", "I don't trust online payments."], "not_this": ["If they won't give card on phone but will sign up online → Rejected CC - Online Signup", "If they have a prepaid card or card was declined → Pre Paid Card"], "confused_with": ["Rejected CC - Online Signup", "Pre Paid Card"]},
    "Rejected CC - Online Signup": {"category": "Payment Issue", "icon": "🖥️", "short": "Won't give card on phone but says they'll complete signup online.", "when": "They're interested but don't want to give payment on the call — they'll do it online.", "examples": ["I'd prefer not to give my card over the phone. I'll sign up online.", "Just send me the link."], "not_this": ["If they refuse card at all (not even online) → Rejected CC"], "confused_with": ["Rejected CC"]},
    "Rejected Subcontracting": {"category": "Service Objection", "icon": "👷", "short": "Customer refuses service because we use subcontractors.", "when": "They specifically say they don't want subcontractors — only direct employees.", "examples": ["I only want employees, not subcontractors.", "I don't trust subcontractors."], "not_this": ["If they have general trust concerns → Handle the trust objection"], "confused_with": ["Already Hired A Provider"]},
    "Services Not Offered": {"category": "Service Objection", "icon": "❌", "short": "Customer wants something we don't provide.", "when": "They want services, features, or payment methods we don't offer.", "examples": ["Can you build me a retaining wall?", "I just need sod installation.", "Do you accept ACH payments?"], "not_this": ["If they want a service we offer but in the wrong region → Out Of Area"], "confused_with": ["Out Of Area", "Oversized Lot"]},
    "Support Call": {"category": "Special Caller", "icon": "🎧", "short": "Existing customer calling about their current account.", "when": "Already a customer — needs help, wants to cancel, billing question, or pending account within 12 hours.", "examples": ["I need help canceling my account.", "I have a question about my last bill."], "not_this": ["If they're a new lead → Regular sales process", "If they spoke with an agent but aren't signed up → Duplicate"], "confused_with": ["Duplicate"]},
    "Next Spring": {"category": "Follow-Up Needed", "icon": "🌸", "short": "⚠️ DO NOT USE — use Callback instead.", "when": "NEVER. If a customer says 'call me next spring,' use Callback and note the timeframe.", "examples": ["I'm not interested now, but call me next spring."], "not_this": ["Always use Callback instead"], "confused_with": ["Callback"]},
    "Test": {"category": "Internal", "icon": "🧪", "short": "Only for system tests and QA checks.", "when": "You're doing a number test or QA check. Never for real calls.", "examples": ["This is a test call."], "not_this": ["Never use for real customer interactions"], "confused_with": []},
    "PF Closed Won": {"category": "Payment Issue", "icon": "✅", "short": "Payment link had issues but customer completed payment after retrying.", "when": "Payment link failed initially but customer got it to work after multiple attempts.", "examples": ["I got it to work after a few tries."], "not_this": ["If it never worked → PF Closed Loss", "If payment went smoothly → Close Won"], "confused_with": ["PF Closed Loss"]},
    "PF Closed Loss": {"category": "Payment Issue", "icon": "⛔", "short": "Lost the sale because the payment link failed.", "when": "Payment link didn't work and customer gave up.", "examples": ["I'm not receiving any links.", "The link is not working."], "not_this": ["If they got it to work → PF Closed Won", "If they refused to give card (not tech) → Rejected CC"], "confused_with": ["PF Closed Won", "Rejected CC"]}
}

disposition_wizard = [
    {"question": "Did you actually talk to the customer?", "options": {"No — voicemail": "Drop Voicemail", "No — dead air / silence": "Dead Air", "No — call dropped mid-conversation": "Disconnected", "Yes — we had a conversation": "next_2"}},
    {"question": "Was it a real potential customer?", "options": {"Wrong number / bad contact info": "Junk Contact", "Telemarketer trying to sell us something": "Not Qualified - Telemarketer", "They want to become a provider for us": "Provider Inquiry", "Existing customer needing support": "Support Call", "Already signed up / spoke with another agent": "Duplicate", "Test / QA call": "Test", "Yes — real potential customer": "next_3"}},
    {"question": "Were you able to have a full conversation?", "options": {"No — they were in a rush, couldn't qualify": "Timing - Unable to Qualify", "No — they want a callback at a later date": "Callback", "No — they said don't contact me again": "Not Qualified - Refuse Contact", "No — not the decision maker": "Not DM", "Yes — full conversation": "next_4"}},
    {"question": "Was there a system or property issue?", "options": {"Address not recognized in system": "Broken Address", "Outside our service area (no price, all red)": "Out Of Area", "We service the area but no crews (price but all red)": "Insufficient Capacity", "Property over 160k sq ft / 3.67 acres": "Oversized Lot", "Can't use app / no email / too complex": "Order Complexity", "No system issues — sales conversation": "next_5"}},
    {"question": "What was the main reason they didn't close?", "options": {"Already hired someone else": "Already Hired A Provider", "Overall price too high": "Price", "Objected to long grass fee": "LGF - Long Grass Fee", "Wants service less often than monthly": "Frequency Minimum", "Won't commit to 3-cut minimum": "Minimum Cuts Requirement", "Needs it within 48 hours, won't wait": "Less Than 48 Hour Turn-Around", "Wants specific arrival time": "Arrival Time", "Wants in-person quote first": "No In-Person Quote", "Doesn't want subcontractors": "Rejected Subcontracting", "Wants services we don't offer": "Services Not Offered", "Property manager — couldn't close": "Property Manager", "Payment issue — next step": "next_6"}},
    {"question": "What was the payment issue?", "options": {"Refused any card (wants cash/check)": "Rejected CC", "Won't give card on phone, will sign up online": "Rejected CC - Online Signup", "Only has prepaid card / card declined": "Pre Paid Card", "Payment link failed but completed after retries": "PF Closed Won", "Payment link failed — lost the sale": "PF Closed Loss"}}
qa_questions = [
    {"category": "Greeting & Opening", "scenario": "A customer calls in. What's the FIRST thing you should do?", "options": {"A": "Ask for their address right away to check availability", "B": "Give the standard greeting and ask what they're looking for", "C": "Tell them about current promotions", "D": "Ask if they've used LawnStarter before"}, "correct": "B", "explanation": "Always start with the standard greeting: 'Hello, this is [NAME] and thank you for calling LawnStarter. Would you mind sharing a bit about what you're looking for?' This sets a professional tone and lets the customer lead with their needs."},
    {"category": "Greeting & Opening", "scenario": "You're calling a customer who was texting with a colleague. What's the correct SMS greeting?", "options": {"A": "Hi, I'm calling about your lawn service inquiry", "B": "Hi, this is ___ with LawnStarter, you were just texting my colleague and they asked me to give you a call. How can I help?", "C": "Hello, is this the homeowner?", "D": "Hi, are you still interested in lawn service?"}, "correct": "B", "explanation": "The SMS greeting should reference that they were texting a colleague: 'Hi, this is ___ with LawnStarter, you were just texting my colleague and they asked me to give you a call. How can I help?' This provides context and a smooth transition."},
    {"category": "Greeting & Opening", "scenario": "After the customer shares what they're looking for, what's a good way to acknowledge their response?", "options": {"A": "Okay, let me transfer you", "B": "Yes! We can take care of all of that! / I can help you with that / Let me look into that for you", "C": "That's not really what we do", "D": "Can you repeat that?"}, "correct": "B", "explanation": "Acknowledge positively and focus on their main interest. Examples: 'Yes! We can take care of all of that!' or 'I can help you with that' or 'Let me look into that for you.' Then ask if they need anything else while we're out there."},
    {"category": "Verification", "scenario": "You need to verify a customer's information. What three things MUST you confirm?", "options": {"A": "Name, email, and credit card", "B": "Address, phone number, and email", "C": "Name, address (with zip), and phone number", "D": "Phone number, frequency preference, and budget"}, "correct": "C", "explanation": "Verification requires: Phone number (mobile or landline), Address (street number, name AND zip), and Name. Email comes later during final verification."},
    {"category": "Verification", "scenario": "When verifying the customer's email at the end of the call, how should you read it back?", "options": {"A": "Just say the email quickly", "B": "Spell it out phonetically (PHONETICALLYSPELLEDOUT@ALWAYS.com)", "C": "Ask them to spell it for you", "D": "Send a confirmation text instead"}, "correct": "B", "explanation": "Always read the email back phonetically to avoid errors. For example: 'I have your email J-O-H-N-D-O-E at G-M-A-I-L dot com.' This prevents miscommunication and ensures accuracy."},
    {"category": "Price Presentation", "scenario": "When presenting the price, what fee must ALWAYS be mentioned separately?", "options": {"A": "Long grass fee", "B": "Tax fee", "C": "$3.99 Trust and Safety fee", "D": "Cancellation fee"}, "correct": "C", "explanation": "Always present: Base Price + $3.99 Trust and Safety fee. This fee helps cover pro vetting and potential property damage mediation. We itemize it for transparency rather than rolling it into the price."},
    {"category": "Price Presentation", "scenario": "A customer asks 'Does the price include taxes?' What should you say?", "options": {"A": "Yes, taxes are included", "B": "This price does not include taxes. Taxes are based on the local laws in your area.", "C": "There are no taxes on lawn services", "D": "I don't know, you'll have to check your bill"}, "correct": "B", "explanation": "Always clarify: 'This price does not include taxes. Taxes are based on the local laws in your area.' Be transparent so there are no surprises on their bill."},
    {"category": "Price Presentation", "scenario": "What services are included in the base lawn mowing price?", "options": {"A": "Just mowing", "B": "Mowing, trimming edges, and blowing off paved surfaces", "C": "Mowing, fertilizing, and weed control", "D": "Mowing and leaf removal"}, "correct": "B", "explanation": "The base mowing service includes: mowing, trimming edges, and blowing off paved surfaces. Also mention the free mobile app and web login for requesting additional services, making account changes, and contacting support."},
    {"category": "3-Cut Minimum", "scenario": "A customer says 'I only need a one-time mow.' What should you do FIRST?", "options": {"A": "Tell them about the 3-cut minimum immediately", "B": "Acknowledge and find out WHY they only want one mow", "C": "Offer them a discount to commit to 3 cuts", "D": "Transfer them to a supervisor"}, "correct": "B", "explanation": "FIRST acknowledge and probe to find out why. Are they selling? Seasonal need? HOA notice? Understanding the reason helps you address their specific concern before discussing the 3-cut minimum."},
    {"category": "3-Cut Minimum", "scenario": "A customer says they're selling their home and only need one mow. What's a good response?", "options": {"A": "Sorry, we can't help with that", "B": "Identify when they're moving, mention single mows elsewhere cost the same, emphasize short-term commitment and getting on schedule now", "C": "We can waive the 3-cut minimum for you", "D": "You should hire a neighbor instead"}, "correct": "B", "explanation": "For selling/moving: Identify when (have they moved already?), note that single mows with other companies are often the same price, emphasize short-term commitment, and create urgency to get on the schedule now."},
    {"category": "3-Cut Minimum", "scenario": "A customer got an HOA notice and says they just need one mow. How should you respond?", "options": {"A": "We only do 3 cuts, sorry", "B": "Long grass means recurring service can help restore the lawn, use us as backup if it happens again, get on schedule now for urgency", "C": "You should call your HOA", "D": "We can come today if you pay extra"}, "correct": "B", "explanation": "For HOA situations: Explain that recurring service helps restore the lawn's look, they can use us as backup if it happens again, and create urgency to get on the schedule now before it gets worse."},
    {"category": "3-Cut Minimum", "scenario": "How should you explain the 48-hour rescheduling policy?", "options": {"A": "You can never change your schedule", "B": "Just let us know 48 hours before the next scheduled cut if you want to make changes", "C": "You have to call to cancel each time", "D": "Changes require a fee"}, "correct": "B", "explanation": "Explain it simply: 'If at any point you would like to make changes to your schedule, just let us know 48 hours before the next scheduled cut.' This emphasizes flexibility while setting clear expectations."},
    {"category": "Scheduling", "scenario": "When providing the service window, what must you always include?", "options": {"A": "Just the days (Wednesday or Thursday)", "B": "Just the dates (July 20th or 21st)", "C": "Days AND dates (Wednesday or Thursday, July 20th or 21st)", "D": "An exact arrival time"}, "correct": "C", "explanation": "Always provide the two-day window with BOTH days AND dates: 'Wednesday or Thursday, starting July 20th or 21st.' Never promise exact times."},
    {"category": "Scheduling", "scenario": "A customer says 'I don't want to wait around all day for the crew.' What should you tell them?", "options": {"A": "You have to be home for the service", "B": "It's contactless - no need to be home. The two-day window allows for weather and routing adjustments.", "C": "We can give you an exact time", "D": "You can call the day before to find out"}, "correct": "B", "explanation": "Emphasize: It's contactless, so no need to be home. The two-day window allows for adjustments due to weather and routing. Also mention the delayed billing/quality check (3-4 days after service)."},
    {"category": "Scheduling", "scenario": "A customer says they need to be home to provide access. What solutions should you offer?", "options": {"A": "We can't service properties that need access", "B": "Can leave notes for gate codes or instructions, and message the pro in advance", "C": "You'll have to take the day off work", "D": "We only service properties with no gates"}, "correct": "B", "explanation": "Offer solutions: They can leave notes with gate codes or special instructions, and message the pro in advance once assigned. This addresses their concern while keeping the flexible window."},
    {"category": "Scheduling", "scenario": "If a customer expresses flexibility with early or late service windows, what should you do?", "options": {"A": "Only mark one option", "B": "Acknowledge their agreement, mark BOTH options, and proceed accordingly", "C": "Tell them to decide later", "D": "Mark neither and let the pro decide"}, "correct": "B", "explanation": "If the customer is flexible, acknowledge their agreement, mark BOTH early and late options, and proceed. This gives more scheduling flexibility while honoring their preferences."},
    {"category": "Long Grass Fee", "scenario": "At what height does the long grass fee potentially apply?", "options": {"A": "Over 6 inches", "B": "Over 9 inches", "C": "Over 12 inches", "D": "Over 15 inches"}, "correct": "B", "explanation": "If grass is over 9 inches, a fee up to the full base mowing price may apply. If over 15 inches, the crew submits a quote for approval before servicing. Always mention this so there are no surprises!"},
    {"category": "Long Grass Fee", "scenario": "What happens if the grass is over 15 inches?", "options": {"A": "We refuse to service it", "B": "The crew will submit a quote for you to approve before servicing", "C": "We charge triple the base price automatically", "D": "We mow it but charge later"}, "correct": "B", "explanation": "If grass is over 15 inches, the crew will submit a quote for the customer to approve BEFORE servicing. This ensures transparency and customer approval for heavily overgrown lawns."},
    {"category": "Long Grass Fee", "scenario": "A customer asks 'How do I know you aren't just charging extra for long grass?' What's the BEST response?", "options": {"A": "You'll just have to trust us", "B": "Pros must submit photos, you get an email when it's assessed, and you can dispute during the 3-day quality check", "C": "We never charge extra unfairly", "D": "You can call support if you disagree"}, "correct": "B", "explanation": "Address with specifics: Pros must supply photos, you get an email immediately, there's a 3-day quality check before charging, and you can dispute with photo review. This builds trust through transparency."},
    {"category": "Long Grass Fee", "scenario": "A customer asks 'Why should I pay extra for long grass?' What's the BEST response?", "options": {"A": "Because that's our policy", "B": "We compensate our pros for additional work. Overgrown lawns take more time and create more wear and tear on equipment.", "C": "Everyone charges this", "D": "You can refuse and we won't mow"}, "correct": "B", "explanation": "Explain the VALUE: We compensate our pros for additional work. Overgrown lawns take more time and create more wear and tear on equipment. This helps them understand it's fair, not arbitrary."},
    {"category": "Objection Handling", "scenario": "What's the correct ORDER for handling objections?", "options": {"A": "Lead with policies, then explain benefits", "B": "Acknowledge, clarify/probe why, then address with value", "C": "Offer a discount immediately, then explain", "D": "Transfer to a supervisor for approval"}, "correct": "B", "explanation": "The correct order: 1) Acknowledge or show understanding, 2) Clarify or probe to find out why, 3) Address with value (what's the benefit?). Never lead with limitations and policies!"},
    {"category": "Objection Handling", "scenario": "What should you NEVER do when handling objections?", "options": {"A": "Show understanding", "B": "Lead with limitations and policies", "C": "Probe to find out why", "D": "Address with value"}, "correct": "B", "explanation": "NEVER lead with limitations and policies. This puts the customer on the defensive. Instead, acknowledge, probe, then address with value and benefits. Policies should support your solution, not lead it."},
    {"category": "48-Hour Window", "scenario": "A customer says 'I have an HOA notice and need service TODAY.' What should you tell them?", "options": {"A": "Sorry, we can't help with urgent requests", "B": "We have the fastest turnaround, and once assigned you can message your pro about availability", "C": "I'll see if I can get a supervisor to approve same-day service", "D": "You should try a different company"}, "correct": "B", "explanation": "Emphasize we have the fastest turnaround time in the industry. Once a pro is assigned, they can message them directly about availability. Also mention we can send a confirmation email they can forward to their HOA."},
    {"category": "48-Hour Window", "scenario": "A customer asks 'Why do I have to wait 48 hours?' What should you explain?", "options": {"A": "Because that's just how it works", "B": "Routes are planned in advance and it gives us time to find a pro. Want me to hold a spot?", "C": "Our pros are lazy", "D": "We're understaffed"}, "correct": "B", "explanation": "Explain: Routes are planned in advance and it gives us time to find a pro in your area. Then offer to hold a spot. This turns a limitation into an action step."},
    {"category": "Cross-Selling", "scenario": "When offering Lawn Treatment, what should you highlight about the service?", "options": {"A": "It's required for all customers", "B": "It includes fertilizer, weed control, and pre-emergent with 7-8 rounds per year", "C": "It replaces the need for mowing", "D": "It's only available in the summer"}, "correct": "B", "explanation": "Lawn Treatment includes fertilizer, weed control, and pre-emergent. For best results: 7-8 rounds per year, every 4-6 weeks. They won't be charged until service is complete. Mention that weed-free lawns can reduce mowing costs!"},
    {"category": "Cross-Selling", "scenario": "What should you tell New York customers about Lawn Treatment?", "options": {"A": "It's not available in New York", "B": "We currently only offer fertilization in your area", "C": "It's the same as everywhere else", "D": "They get a discount"}, "correct": "B", "explanation": "For New York customers specifically: 'We currently only offer fertilization in your area.' This sets correct expectations about what's available in their region."},
    {"category": "Cross-Selling", "scenario": "If a customer says NO to an additional service, what should you do?", "options": {"A": "Keep pushing until they say yes", "B": "Just move on without saying anything", "C": "Remind them it can be added anytime via the app/portal", "D": "Offer a bigger discount"}, "correct": "C", "explanation": "If they say no, remind them they can always add services anytime via the app or portal, or contact support for services not available there. Don't push, but leave the door open!"},
    {"category": "Cross-Selling", "scenario": "When cross-selling Leaf Removal, what should you ask to identify the need?", "options": {"A": "Do you want leaf removal?", "B": "Are there any leaves or small twigs on your lawn?", "C": "Is it fall time?", "D": "Do you have trees?"}, "correct": "B", "explanation": "Ask specifically: 'Are there any leaves or small twigs on your lawn?' This identifies the actual need. If yes, offer the IQ Cleanup quote and set expectations about what happens if excessive leaves are found at service time."},
    {"category": "Cross-Selling", "scenario": "What expectation should you set about leaves and mowing?", "options": {"A": "We always mow over leaves", "B": "If excessive leaves need to be picked up before mowing, we'll quote for cleanup which could delay service completion", "C": "We never mow if there are leaves", "D": "Leaves don't affect mowing"}, "correct": "B", "explanation": "Set the expectation: 'If the crew arrives and there's an excessive amount of leaves that need picked up before we can mow, we'll need to quote you for the cleanup, wait for your approval, which could prolong your service completion.'"},
    {"category": "Cross-Selling", "scenario": "When pitching Lawn Treatment, what optional benefit can you mention about weeds and mowing?", "options": {"A": "Weeds make lawns look nicer", "B": "Weeds grow first, make lawns appear overgrown, and controlling them can reduce mowing frequency and costs", "C": "Weeds have no effect on mowing", "D": "We charge less if you have weeds"}, "correct": "B", "explanation": "Optional context: Weeds are the first to grow, making the lawn appear overgrown or warrant additional fees. Keeping weeds in check minimizes overall growth, reducing the need for more frequent mowing."},
    {"category": "Property Details", "scenario": "A customer has outdoor pets. What TWO things should you tell them?", "options": {"A": "We can't service properties with pets", "B": "Pets should be secured during service AND please pick up pet waste", "C": "The pro will handle the pets", "D": "They need to pay an extra pet fee"}, "correct": "B", "explanation": "Two requirements: 1) Pets should be secured during service time, 2) Please pick up any pet waste on the property. If excessive waste is found, the crew will mow around it."},
    {"category": "Property Details", "scenario": "A customer has a property gate. What should you ask?", "options": {"A": "Just ask if they have a gate", "B": "Ask if it's wide enough for a riding mower, if it's a gated community, and if there's a code or special instructions", "C": "Tell them we can't service gated properties", "D": "Ask them to leave it open forever"}, "correct": "B", "explanation": "For property gates: Is it wide enough for a riding mower? For community gates: Is there a gate code or special instructions? Include access details in the 'Special Neighborhood Access' field. Be concise!"},
    {"category": "Property Details", "scenario": "Where should you include special access details?", "options": {"A": "Just tell the customer verbally", "B": "In the 'Special Neighborhood Access' field on the work order", "C": "In an email to the pro", "D": "Nowhere, the pro will figure it out"}, "correct": "B", "explanation": "Include special access details in the 'Special Neighborhood Access' field on the work order. Keep in mind the importance of being concise so the information is clear and usable."},
    {"category": "Payment", "scenario": "A customer asks 'Why do I have to put a card on file?' What's the BEST response?", "options": {"A": "It's just our policy", "B": "You don't need to be home, we charge 3 days AFTER service so you can address any issues first", "C": "We need it for security purposes", "D": "You can pay cash if you prefer"}, "correct": "B", "explanation": "Focus on benefits: No need to be home when service happens, and we charge 3 days AFTER completion — giving time to address any service issues before being charged. We send notifications when service is complete."},
    {"category": "Payment", "scenario": "When collecting payment info, what do you tell the customer?", "options": {"A": "Give me your card number", "B": "I'm sending a secure link via text and email since we don't have access to payment info on our end", "C": "You can pay after the first service", "D": "We'll call back later for payment"}, "correct": "B", "explanation": "Always say: 'I'm sending over a secure link for you to add your payment info directly, since we don't have access to that on our end. This will go through text and email.' We never take card info verbally!"},
    {"category": "Payment", "scenario": "A customer is worried about security with online payment. What can you tell them about Stripe?", "options": {"A": "I don't know anything about it", "B": "Stripe is highly secure and used by large businesses like Walmart and Amazon, used by millions", "C": "It's pretty safe I guess", "D": "You can mail a check instead"}, "correct": "B", "explanation": "Reassure them: Stripe is highly secure and used by large businesses like Walmart and Amazon — used by millions. Also remind them we charge 3 days after completion and send notifications when service is done."},
    {"category": "Payment", "scenario": "A customer says 'I don't like recurring charges.' What should you emphasize?", "options": {"A": "You have to accept them", "B": "We only charge if a service is completed, send notifications when done, and charge 3 days AFTER service", "C": "You can cancel anytime", "D": "Everyone does recurring charges"}, "correct": "B", "explanation": "Emphasize: We only charge if a service is completed. We send email and app notifications as soon as service is done. We only charge 3 days AFTER the service. This gives them control and transparency."},
    {"category": "Closing", "scenario": "What should you tell the customer to expect AFTER the call?", "options": {"A": "Nothing, just say goodbye", "B": "Email when a pro picks up the job, text with app link and temp password, and they can message the pro directly", "C": "A pro will call them back", "D": "They need to call back to confirm"}, "correct": "B", "explanation": "Set expectations: 1) Email confirming a pro picked up the job + their two-day window, 2) Text with app link and temporary password (email is username), 3) They can message their pro directly once assigned!"},
    {"category": "Closing", "scenario": "What's the LAST thing you should do before ending the call?", "options": {"A": "Hang up quickly to take the next call", "B": "Ask 'Any other questions before I let you go?' and direct them to support via app/portal", "C": "Try to sell one more service", "D": "Transfer them to QA"}, "correct": "B", "explanation": "Always ask 'Any other questions before I let you go?' Then direct them to the Support Team via app or portal for future questions. End with 'Thank you for choosing LawnStarter. Have a great day!'"},
    {"category": "Closing", "scenario": "For landline-only customers, how should you explain logging into the website?", "options": {"A": "They can't use the website", "B": "Enter email address, click forgot password, receive temp password via email, change password once logged in", "C": "Call support for help", "D": "They have to use the app instead"}, "correct": "B", "explanation": "For landline customers: 'Enter your email address and click the forgot your password option. You'll receive an email with a temporary password. Make sure to change the password once you log in.' This helps non-app users access their account."},
    {"category": "Closing", "scenario": "What referral opportunity should you mention in the introduction email?", "options": {"A": "There's no referral program", "B": "Recommend us on NextDoor and receive a $20 credit to your account", "C": "Refer friends for a discount", "D": "Leave a Google review for $50"}, "correct": "B", "explanation": "Mention: 'In your introduction email, you will see a button about recommending us on NextDoor. Do this and receive a $20 credit to your account.' This encourages referrals and rewards the customer."},
    {"category": "Not DM", "scenario": "You're speaking with someone who ISN'T the decision maker. What's REQUIRED before ending the call?", "options": {"A": "Just say goodbye and call back later", "B": "Educate on value and offer to hold a spot", "C": "Ask them to have the DM call back", "D": "Send an email to the DM"}, "correct": "B", "explanation": "When speaking with non-DM: Probe if DM is available, educate on value (flexibility, app benefits, quality check), and ALWAYS offer to hold a spot. Holding a spot is REQUIRED for non-DM calls."},
    {"category": "Not DM", "scenario": "If the decision maker IS available when you're speaking with a non-DM, what should you do?", "options": {"A": "Just continue with the non-DM", "B": "Offer to speak with the decision maker", "C": "Ask them to call back", "D": "End the call"}, "correct": "B", "explanation": "If the DM is available, offer to speak with them directly. This gives you the best chance of closing the sale with the person who can actually make the decision."},
    {"category": "Not DM", "scenario": "If the DM is NOT available, what should you ask the non-DM?", "options": {"A": "When will they be back?", "B": "Does the DM have specific needs or concerns?", "C": "Can they make the decision instead?", "D": "Should we call back tomorrow?"}, "correct": "B", "explanation": "Ask: 'Does [DM] have specific needs or concerns?' This helps you understand what's important to the actual decision maker so you can address those points and educate on value."},
    {"category": "Trust & Safety Fee", "scenario": "A customer asks 'Why do I have to pay the Trust & Safety fee?' What should you say?", "options": {"A": "It's just an extra charge we add", "B": "It helps cover pro vetting and mediate potential property damage — most companies roll it into price, we itemize for transparency", "C": "You can skip it if you want", "D": "It's a government requirement"}, "correct": "B", "explanation": "The T&S fee covers the pro vetting process and helps mediate potential property damage. Most companies roll it into their price — we itemize it for transparency. Most local providers don't provide any coverage at all!"},
    {"category": "Frequency Objections", "scenario": "A customer says 'I don't want to be locked into a schedule.' What should you emphasize?", "options": {"A": "You have to commit to the schedule", "B": "Flexible options: reschedule, skip, pause — manage via app or message your pro — can change frequency as needed", "C": "Just cancel if you don't like it", "D": "We'll call you before each service"}, "correct": "B", "explanation": "Emphasize flexibility: reschedule, skip, or pause options. Manage everything on the app or communicate with your pro directly. Can change frequency as needed. Regular maintenance = healthier lawn!"},
